# Read H-Reflex App Data Files

This notebook reads and visualizes data from the **H-Reflex Behavior App** (hreflex_txbdc) binary data files.

**File convention (V2/V3):**
- **`.hrs1`** — MH Recruitment Curve stage: sweeps across stimulation intensities to map the M/H-wave recruitment curve.
- **`.hrs2`** — Control Mode stage: stimulates at a fixed user-set intensity (can be changed between trials).
- **`.hrs3`** — Down Condition Pellet (DCP) stage: closed-loop H-reflex conditioning with pellet reward.
- **`.hrs4`** — Up Condition Pellet stage.
- **`.hrs5`** — Down Condition VNS stage.
- **`.hrs6`** — Up Condition VNS stage.
- **`.hrsft`** — Frequency Test stage.

All trial files share the MhRecHeader + MhRecTrial binary format.
EMG data blocks (raw differential, filtered, abs-value) are embedded in every file.

The binary format is based on the `FileIO_Helpers` serialization from the `hreflex_txbdc` package.

# Section 1: Binary File Reader Utilities

In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
from helpers import (
    # File readers
    read_hrs2, read_hrs3, read_hrs4, read_hrs5, read_hrs6, read_hrs_ft,
    find_hrs_files, detect_app_version,
    # Summary printers
    print_hrs2_summary,
    # HRS2 plots
    plot_amplitude_distribution, plot_background_emg_views, plot_hrs2_analysis,
    plot_actual_trial_timeline, plot_mwave_control_error, plot_frequency_test,
    plot_mwave_stabilization_groups, compute_mwave_size,
    # Frequency Test analysis plots
    plot_ft_depression_curve, plot_ft_averaged_waveforms, plot_ft_peak_curve,
    # SNR analysis
    compute_snr_analysis, compute_mra_snr_analysis,
    compute_peri_stim_bg, PERI_STIM_BG_START_MS, PERI_STIM_BG_END_MS,
    plot_hrs2_trials, classify_trials, get_trial_window,
    detect_stim_onset, get_trial_context_window,
    detect_and_correct_failed_trials, make_failed_trials_viewer,
    exclude_failed_trials, filter_recordings_by_metric,
    # Post-hoc global windowing analysis
    analyze_global_background, run_threshold_sweep, plot_threshold_sweep,
    split_trials_by_polarity, plot_hm_ratio_summary, plot_hwave_regression,
    # Constants
    SAMPLE_RATE, BIN_DURATION_MS, BIN_SAMPLES, TRIAL_RECORD_MS,
    STIM_ONSET_THRESHOLD, STIM_END_THRESHOLD,
    build_merged_amp_groups,
    make_viewer, make_ft_viewer, compute_h_comparison_data, plot_h_reflex_comparison,
    load_all_recordings, FT_SNAP_HZ, build_settings_dataframe,
)

print("Helpers loaded.")
print(f"  App constants: SAMPLE_RATE={SAMPLE_RATE} Hz | BIN={BIN_DURATION_MS} ms ({BIN_SAMPLES} samples) | TRIAL_RECORD={TRIAL_RECORD_MS} ms")
print(f"  Stim thresholds: onset >= {STIM_ONSET_THRESHOLD} V | end < {STIM_END_THRESHOLD} V")

Helpers loaded.
  App constants: SAMPLE_RATE=5000.0 Hz | BIN=50 ms (250 samples) | TRIAL_RECORD=100 ms
  Stim thresholds: onset >= 4.5 V | end < 1.9 V

# Section 1b: Auto-Detect Recording Files

Set `recording_dir` to the path of your recording folder.  
The `.hrs1` and `.hrs2` files will be found automatically.

In [2]:
# ── Multi-Recording Configuration ─────────────────────────────────────────────
# Each entry: ("Display Label", "relative/path/to/recording_dir", sample_rate_hz)
# sample_rate_hz: explicit Hz (e.g. 10000.0 or 5000.0); None = auto-detect from data.
RECORDING_DIRS = [
    

    #("HRPILOT-17 CM1",  "HRPilot-17_Control/BASELINE1_HRPILOT-17_BOOTH1_250US_10KHZ_8-20-26",        10000.0),
    #("HRPILOT-17 CM2",  "HRPilot-17_Control/BASELINE2_HRPILOT-17_BOOTH1_250US_10KHZ_8-21-26",        10000.0),
    #("HRPILOT-17 CM3",  "HRPilot-17_Control/BASELINE3_HRPILOT-17_BOOTH1_250US_10KHZ_8-24-26",        10000.0),
    #("HRPILOT-17 CM4",  "HRPilot-17_Control/BASELINE4_HRPILOT-17_BOOTH1_250US_10KHZ_8-25-26",        10000.0),
    #("HRPILOT-17 CM5",  "HRPilot-17_Control/BASELINE5_HRPILOT-17_BOOTH1_250US_10KHZ_8-26-26",        10000.0),
    #("HRPILOT-17 CM6",  "HRPilot-17_Control/BASELINE6_HRPILOT-17_BOOTH1_250US_10KHZ_8-27-26",        10000.0),
    #("HRPILOT-17 CM7",  "HRPilot-17_Control/BASELINE7_HRPILOT-17_BOOTH1_250US_10KHZ_8-28-26",        10000.0),
    
    
    # Frequency Tests
    #("HRPILOT-17 FT1",  "HRPilot-17_Control/CCC1_HRPILOT-17_BOOTH1_10KHZ_250US_8-5-26",        10000.0),
    #("HRPILOT-17 FT2",  "HRPilot-17_Control/CCC2_HRPILOT-17_BOOTH1_10KHZ_250US_8-5-26",        10000.0),
    #("HRPILOT-17 Offline FT3",  "HRPilot-17_Control/OFFLINE_FREQTEST1_HRPILOT-17_BOOTH1_10KHZ_250US_8-14-26",        10000.0),
    #("HRPILOT-17 Online FT4",  "HRPilot-17_Control/Old/ONLINE_FREQTEST1_HRPILOT-17_BOOTH1_10KHZ_250US_8-14-26",        10000.0),
        
    
    # Upconditioning days
    #("HRPILOT-17 UPC1",  "HRPilot-17_Up_Cond_Pellet/UPCP1_HRPILOT-17_250US_10KHZ_8-31-26",              10000.0),
    #("HRPILOT-17 UPC2",  "HRPilot-17_Up_Cond_Pellet/UPCP2_HRPILOT-17_250US_10KHZ_9-1-26",               10000.0),
    #("HRPILOT-17 UPC3",  "HRPilot-17_Up_Cond_Pellet/UPCP3_HRPILOT-17_250US_10KHZ_9-2-26",               10000.0),
    #("HRPILOT-17 UPC4",  "HRPilot-17_Up_Cond_Pellet/UPCP4_HRPILOT-17_BOOTH1_250US_10KHZ_9-3-26",        10000.0),
    #("HRPILOT-17 UPC5",  "HRPilot-17_Up_Cond_Pellet/UPCP5_HRPILOT-17_BOOTH1_500US_10KHZ_9-4-26",        10000.0),
    #("HRPILOT-17 UPC6",  "HRPilot-17_Up_Cond_Pellet/UPCP6_HRPILOT-17_BOOTH1_500US_10KHZ_9-8-26",        10000.0),
    
    # HRPilot-25 Recordings
    #("Calib4 HRPILOT-25 250US",  "Calibration/HRPilot-25/CALIB4_HRPILOT-25_BOOTH2_100US_10KHZ_9-22-26",        10000.0),

    
    # HRPilot-27 Recordings
    #("Calib1 HRPILOT-27 250US",  "Calibration/HRPilot-27/CALIB1_FILTFILT_HRPILOT-27_BOOTH2_250US_10KHZ_9-23-26",        10000.0),
    #("Calib2 HRPILOT-27 250US",  "Calibration/HRPilot-27/CALIB2_HRPILOT-27_BOOTH3_100US_10KHZ_9-29-26",        10000.0),
    #("CM1 HRPILOT-27 100US",  "Calibration/HRPilot-27/CM1_HRPILOT-27_BOOTH4_100US_10KHZ_10-2-26",        10000.0),
    
    
    # HRPilot-33 Recordings
    #("Calib1 HRPILOT-33 250US",  "Calibration/HRPilot-33/CALIB1_HRPILOT-33_BOOTH1_250US_10KHZ_9-21-26",        10000.0),
    #("Calib1PT2 HRPILOT-33 250US",  "Calibration/HRPilot-33/CALIB1_PT2_HRPILOT-33_BOOTH1_250US_10KHZ_9-21-26",        10000.0),
    #("Calib1PT2 HRPILOT-33 250US",  "Calibration/HRPilot-33/CALIB1_PT2_HRPILOT-33_BOOTH1_250US_10KHZ_9-21-26",        10000.0),
    #("CM1 HRPILOT-33 250US",  "Calibration/HRPilot-33/CM1_FILTFILT_HRPILOT-33_BOOTH3_250US_10KHZ_9-28-26",        10000.0),
    #("CM2 HRPILOT-33 250US",  "Calibration/HRPilot-33/CM2_HRPILOT-33_BOOTH3_100US_10KHZ_9-30-26",        10000.0),
    #("CM2 FT HRPILOT-33 250US",  "Calibration/HRPilot-33/CM2_HRPILOT-33_BOOTH3_250US_10KHZ_9-30-26",        10000.0),
    #("CM3 HRPILOT-33 250US",  "Calibration/HRPilot-33/CM3_HRPILOT-33_BOOTH3_250US_10KHZ_10-1-26",        10000.0),
    #("CM4 HRPILOT-33 250US",  "Calibration/HRPilot-33/CM4_HRPILOT-33_BOOTH3_250US_10KHZ_10-2-26",        10000.0),
        
    # HRPilot-34 Recordings
    #("Calib4 HRPILOT-34 100US",  "Calibration/HRPilot-34/CALIB4_FILTFILT_HRPILOT-34_BOOTH1_250US_10KHZ_9-23-26",        10000.0),
    ("CM1 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM1_FILTFILT_HRPILOT-34_BOOTH1_250US_10KHZ_9-24-26",        10000.0),
    ("CM2 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM2_FILTFILT_FIXED_HRPILOT-34_BOOTH2_250US_10KHZ_9-25-26",        10000.0),
    ("CM3 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM3_HRPILOT-34_BOOTH1_250US_10KHZ_9-28-26",        10000.0),
    ("CM4 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM4_HRPILOT-34_BOOTH1_250US_10KHZ_9-30-26",        10000.0),
    ("CM5 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM5_HRPILOT-34_BOOTH1_250US_10KHZ_10-1-26",        10000.0),
    ("CM6 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM6_HRPILOT-34_BOOTH1_250US_10KHZ_10-2-26",        10000.0),
    ("CM7 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM7_HRPILOT-34_BOOTH1_250US_10KHZ_10-5-26",        10000.0),
    ("CM8 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM8_HRPILOT-34_BOOTH3_250US_10KHZ_10-6-26",        10000.0),
    ("CM9 HRPILOT-34 250US",  "Calibration/HRPilot-34/CM9_HRPILOT-34_BOOTH3_250US_10KHZ_10-7-26",        10000.0),
        
    
    
    
    
    
    # HRPilot-36 Recordings
    #("Calib2 HRPILOT-36 250US",  "Calibration/HRPilot-36/CALIB2_HRPILOT-36_BOOTH2_250US_10KHZ_9-10-26",        10000.0),
    #("CM1 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM1_HRPILOT-36_BOOTH2_250US_10KHZ_9-14-26",        10000.0),
    #("CM2 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM2_HRPILOT-36_BOOTH2_250US_10KHZ_9-15-26",        10000.0),
    #("CM3 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM3_HRPILOT-36_BOOTH2_250US_10KHZ_9-17-26",        10000.0),
    #("CM3 FT OFfline HRPILOT-36 250US",  "Calibration/HRPilot-36/CM3_FT_OFFLINE_HRPILOT-36_BOOTH2_250US_10KHZ_9-17-26",        10000.0),
    #("CM4 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM4_HRPILOT-36_BOOTH1_250US_10KHZ_9-18-26",        10000.0),
    #("CM5 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM5_HRPILOT-36_BOOTH1_250US_10KHZ_9-21-26",        10000.0),
    #("CM6 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM6_HRPILOT-36_BOOTH1_250US_10KHZ_9-22-26",        10000.0),
    #("CM7 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM7_FILTFILT_HRPILOT-36_BOOTH2_250US_10KHZ_9-23-26",        10000.0),
    #("CM8 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM8_FILTFILT_HRPILOT-36_BOOTH2_250US_10KHZ_9-24-26",        10000.0),
    #("CM8 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM9_FILTFILT_FIXED_HRPILOT-36_BOOTH1_250US_10KHZ_9-25-26",        10000.0),
    #("CM9 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM9_FILTFILT_FIXED_HRPILOT-36_BOOTH1_250US_10KHZ_9-25-26",        10000.0),
    #("CM10 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM10_FILTFILT_HRPILOT-36_BOOTH2_250US_10KHZ_9-28-26",        10000.0),
    #("CM11 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM11_FILTFILT_HRPILOT-36_BOOTH2_250US_10KHZ_9-29-26",        10000.0),
    #("CM12 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM12_HRPILOT-36_BOOTH2_250US_10KHZ_9-30-26",        10000.0),
    #("CM13 HRPILOT-36 250US",  "Calibration/HRPilot-36/CM13_HRPILOT-36_BOOTH2_250US_10KHZ_10-1-26",        10000.0),
    
    #("CM13 HRPILOT-36 250US",  "Up-Conditioning_VNS/HRPilot-36/UPVNS1_HRPILOT-36_BOOTH2_250US_10KHZ_10-2-26",        10000.0),
    
    
    
    
    #HRPilot-19 Recordings
    #("Calib1 HRPILOT-19 250US",  "Calibration/HRPilot-19/CALIB1_HRPILOT-19_BOOTH2_250US_10KHZ_9-18-26",        10000.0),
    
    #HRPilot-21 Recordings
    #("Calib1 HRPILOT-21 250US",  "Calibration/HRPilot-21/CALIB1_HRPILOT-21_BOOTH1_250US_10KHZ_9-18-26",        10000.0),
        
    
    
]
# When multiple recordings are loaded a Recording dropdown appears in the selector cell.
print(f"{len(RECORDING_DIRS)} recording(s) configured.")
for _i, (_lbl, _rdir, _rsr) in enumerate(RECORDING_DIRS):
    _sr_str = f"{_rsr} Hz" if _rsr else "auto-detect"
    print(f"  [{_i}] {_lbl!r}  →  {_rdir}  (sample_rate={_sr_str})")

9 recording(s) configured.
  [0] 'CM1 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM1_FILTFILT_HRPILOT-34_BOOTH1_250US_10KHZ_9-24-26  (sample_rate=10000.0 Hz)
  [1] 'CM2 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM2_FILTFILT_FIXED_HRPILOT-34_BOOTH2_250US_10KHZ_9-25-26  (sample_rate=10000.0 Hz)
  [2] 'CM3 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM3_HRPILOT-34_BOOTH1_250US_10KHZ_9-28-26  (sample_rate=10000.0 Hz)
  [3] 'CM4 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM4_HRPILOT-34_BOOTH1_250US_10KHZ_9-30-26  (sample_rate=10000.0 Hz)
  [4] 'CM5 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM5_HRPILOT-34_BOOTH1_250US_10KHZ_10-1-26  (sample_rate=10000.0 Hz)
  [5] 'CM6 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM6_HRPILOT-34_BOOTH1_250US_10KHZ_10-2-26  (sample_rate=10000.0 Hz)
  [6] 'CM7 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM7_HRPILOT-34_BOOTH1_250US_10KHZ_10-5-26  (sample_rate=10000.0 Hz)
  [7] 'CM8 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM8_HRPILOT-34_BOOTH3_250US_10KHZ_10-6-26  (sample_rate=10000.0 Hz)
  [8] 'CM9 HRPILOT-34 250US'  →  Calibration/HRPilot-34/CM9_HRPILOT-34_BOOTH3_250US_10KHZ_10-7-26  (sample_rate=10000.0 Hz)

In [3]:
# ── Load all recordings (auto-detects V2 / V3) ─────────────────────────────────
# Customize FT_SNAP_HZ to match your experiment's pulse-train frequencies (Hz).
# Values within ±25% of a target snap to that target.
FT_SNAP_HZ_CUSTOM = FT_SNAP_HZ  # use [5.0, 10.0, 15.0, 20.0, 33.0] or override here

_all_recordings_raw = load_all_recordings(RECORDING_DIRS, ft_snap_hz_list=FT_SNAP_HZ_CUSTOM)
# Analysis cells use _all_recordings; the Trial Exclusion section below
# replaces it with a cleaned copy. _all_recordings_raw is never modified.
_all_recordings = _all_recordings_raw
_active_rec_label = next(iter(_all_recordings))
print(f'\n{len(_all_recordings)} recording(s) loaded.  Active: {_active_rec_label!r}')

── Loading: 'CM1 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM1_FILTFILT_HRPILOT-34_BOOTH1_250US_10KHZ_9-24-26)
   .hrs1: not found
   .hrs2: 847 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM1 HRPILOT-34 250US/Control Mode (.hrs2): 847/847 trials rebuilt (raw→diff→filtfilt ±200 ms)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz
   Settings sidecars: 1/1 stage(s)

── Loading: 'CM2 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM2_FILTFILT_FIXED_HRPILOT-34_BOOTH2_250US_10KHZ_9-25-26)
   .hrs1: not found
   .hrs2: 1074 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM2 HRPILOT-34 250US/Control Mode (.hrs2): 1062/1074 trials rebuilt (raw→diff→filtfilt ±200 ms)  (12 kept stored — alignment miss)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz

── Loading: 'CM3 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM3_HRPILOT-34_BOOTH1_250US_10KHZ_9-28-26)
   .hrs1: not found
   .hrs2: 805 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM3 HRPILOT-34 250US/Control Mode (.hrs2): 788/805 trials rebuilt (raw→diff→filtfilt ±200 ms)  (17 kept stored — alignment miss)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz
   Settings sidecars: 1/1 stage(s)

── Loading: 'CM4 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM4_HRPILOT-34_BOOTH1_250US_10KHZ_9-30-26)
   .hrs1: not found
   .hrs2: 808 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM4 HRPILOT-34 250US/Control Mode (.hrs2): 808/808 trials rebuilt (raw→diff→filtfilt ±200 ms)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz
   Settings sidecars: 1/1 stage(s)

── Loading: 'CM5 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM5_HRPILOT-34_BOOTH1_250US_10KHZ_10-1-26)
   .hrs1: not found
[read_hrs2] fv=17>=15 Control Mode: pre-scanning for trial positions …
[read_hrs2] Found 800 trial block(s)
[read_hrs2] Read 219403 EMG block(s)
   .hrs2: 800 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM5 HRPILOT-34 250US/Control Mode (.hrs2): 788/800 trials rebuilt (raw→diff→filtfilt ±200 ms)  (12 kept stored — alignment miss)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz
   Settings sidecars: 1/1 stage(s)

── Loading: 'CM6 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM6_HRPILOT-34_BOOTH1_250US_10KHZ_10-2-26)
   .hrs1: not found
[read_hrs2] fv=17>=15 Control Mode: pre-scanning for trial positions …
[read_hrs2] Found 953 trial block(s)
[read_hrs2] Read 304292 EMG block(s)
   .hrs2: 953 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM6 HRPILOT-34 250US/Control Mode (.hrs2): 953/953 trials rebuilt (raw→diff→filtfilt ±200 ms)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz
   Settings sidecars: 1/1 stage(s)

── Loading: 'CM7 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM7_HRPILOT-34_BOOTH1_250US_10KHZ_10-5-26)
   .hrs1: not found
[read_hrs2] fv=17>=15 Control Mode: pre-scanning for trial positions …
[read_hrs2] Found 990 trial block(s)
[read_hrs2] Read 184734 EMG block(s)
   .hrs2: 990 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM7 HRPILOT-34 250US/Control Mode (.hrs2): 990/990 trials rebuilt (raw→diff→filtfilt ±200 ms)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz
   Settings sidecars: 1/1 stage(s)

── Loading: 'CM8 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM8_HRPILOT-34_BOOTH3_250US_10KHZ_10-6-26)
   .hrs1: not found
[read_hrs2] fv=17>=15 Control Mode: pre-scanning for trial positions …
[read_hrs2] Found 589 trial block(s)
[read_hrs2] Read 197972 EMG block(s)
   .hrs2: 589 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM8 HRPILOT-34 250US/Control Mode (.hrs2): 589/589 trials rebuilt (raw→diff→filtfilt ±200 ms)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz
   Settings sidecars: 1/1 stage(s)

── Loading: 'CM9 HRPILOT-34 250US'  (Calibration/HRPilot-34/CM9_HRPILOT-34_BOOTH3_250US_10KHZ_10-7-26)
   .hrs1: not found
[read_hrs2] fv=17>=15 Control Mode: pre-scanning for trial positions …
[read_hrs2] Found 836 trial block(s)
[read_hrs2] Read 266173 EMG block(s)
   .hrs2: 836 trials  (Control Mode)
   Note: Control Mode aliased as primary analysis (no MH Recruitment stage).
   [OFFLINE] CM9 HRPILOT-34 250US/Control Mode (.hrs2): 836/836 trials rebuilt (raw→diff→filtfilt ±200 ms)
   App V3  |  Stages: ['control_mode']  |  SR: 10000.0 Hz
   Settings sidecars: 1/1 stage(s)

9 recording(s) loaded.  Active: 'CM1 HRPILOT-34 250US'

# Section 3: Peri-Stimulus Trials — MH Recruitment Curve or Control Mode

`hrs2_trials` contains whichever stage was run:
- `.hrs1` present → MH Recruitment Curve trials
- `.hrs1` absent, `.hrs2` present → Control Mode trials (aliased automatically)

In [4]:
# Stage summary for the active recording
print(f'Active recording: {_active_rec_label!r}')
_rec_info = _all_recordings[_active_rec_label]
for _sk, (_st, _sh, _se, _slbl) in _rec_info['stage_map'].items():
    print(f'  {_slbl}: {len(_st)} trials')
print(f'\n(Run the Stage Selector cell below to enable the interactive dropdown.)')

Active recording: 'CM1 HRPILOT-34 250US'
  Control Mode (.hrs2): 847 trials

(Run the Stage Selector cell below to enable the interactive dropdown.)

In [5]:
# ── Recording & Stage Viewer Factory ───────────────────────────────────────────
# Each viewer section below has its own independent Recording + Stage dropdowns.
# Set each viewer to a different recording/stage to compare them side by side.
# make_viewer() is defined in helpers.py
from IPython.display import display as _disp

# ── Loaded recordings summary ────────────────────────────────────────────────────
print(f'{len(_all_recordings)} recording(s) loaded:')
for _rl, _rd in _all_recordings.items():
    print(f'  {_rl!r}  (App V{_rd["app_version"]}  |  {_rd["sample_rate"]} Hz)')
    for _sk, (_st, _sh, _se, _slbl) in _rd['stage_map'].items():
        print(f'    · {_slbl}: {len(_st)} trials')
print()
print('Each viewer below has its own Recording + Stage dropdowns for independent selection.')

# ── Stimulation Intensity Histogram ─────────────────────────────────────────────────────
def _render_hist(trials, header, emg_blocks, stage_label, rec_label, sr, h1h):
    print(f'\n── Histogram: {stage_label}  ({len(trials)} trials)  [{rec_label}]')
    plot_amplitude_distribution(trials, header)

_hist_widget, _hist_render = make_viewer(_all_recordings, _active_rec_label, _render_hist)
_disp(_hist_widget)
_hist_render()

9 recording(s) loaded:
  'CM1 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 847 trials
  'CM2 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 1074 trials
  'CM3 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 805 trials
  'CM4 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 808 trials
  'CM5 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 800 trials
  'CM6 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 953 trials
  'CM7 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 990 trials
  'CM8 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 589 trials
  'CM9 HRPILOT-34 250US'  (App V3  |  10000.0 Hz)
    · Control Mode (.hrs2): 836 trials

Each viewer below has its own Recording + Stage dropdowns for independent selection.

VBox(children=(Dropdown(description='Recording:', layout=Layout(width='600px'), options=('CM1 HRPILOT-34 250US…

In [6]:
# ── Trial Timeline ─────────────────────────────────────────────────────────────
from IPython.display import display as _disp

def _render_tl(trials, header, emg_blocks, stage_label, rec_label, sr, h1h):
    print(f'\n── Trial Timeline: {stage_label}  ({len(trials)} trials)  [{rec_label}]')
    plot_actual_trial_timeline(trials, header=header)

_tl_widget, _tl_render = make_viewer(_all_recordings, _active_rec_label, _render_tl)
_disp(_tl_widget)
_tl_render()

VBox(children=(Dropdown(description='Recording:', layout=Layout(width='600px'), options=('CM1 HRPILOT-34 250US…

# Section 3b: "Most Recent Background" + "Background EMG Level"

Recreates the H-Reflex App recruitment-curve trial-plot widgets from `MhRecruitmentCurveStage.get_trial_plot_options`:

- **Most recent background** bar chart of the pre-stim |EMG| bins.
- **EMG Level** scatter of background grand means across trials.

Bins are reconstructed from `hrs2_emg_blocks` over a fixed monitoring window (default 2500 ms ending at trigger time).

In [7]:
# ── Background EMG Views ──────────────────────────────────────────────────────
from IPython.display import display as _disp

def _render_bg(trials, header, emg_blocks, stage_label, rec_label, sr, h1h):
    print(f'\n── Background EMG: {stage_label}  ({len(trials)} trials)  [{rec_label}]')
    plot_background_emg_views(trials, emg_blocks, monitoring_window_ms=2500)

_bg_widget, _bg_render = make_viewer(_all_recordings, _active_rec_label, _render_bg)
_disp(_bg_widget)
_bg_render()

VBox(children=(Dropdown(description='Recording:', layout=Layout(width='600px'), options=('CM1 HRPILOT-34 250US…

In [8]:
#  Configuration 
PRE_PLOT_MS  = 2   # ms before stim onset to display
POST_PLOT_MS = 15  # ms after  stim onset to display
N_PER_PAGE   = 6   # trials shown per page (2 rows x 3 cols)

# M/H wave window constants (ms relative to stim onset)
M_WAVE_START_MS = 2
M_WAVE_END_MS   = 4
H_WAVE_START_MS = 6
H_WAVE_END_MS   = 10

PRE_AVG_MS  = 2   # ms before stim onset
POST_AVG_MS = 15  # ms after  stim onset
N_PER_PAGE  = 6   # amplitude groups per page (2 rows x 3 cols)

In [9]:
# ── Failed / Alignment-Miss Trial Viewer ──────────────────────────────────────
# Shows trials where offline xcorr reconstruction failed (stored app-filtered data kept).
# Controls mirror make_ft_viewer: Y auto/min/max, Fig W/H, Pre/Post ms.
# Subplots: Show Stim ADC, Show Sync (analog), Show Sync DIG IN (step-function TTL).
#
# Red dashed line = stored onset (onset_sample_index)
# Orange dotted line = stored stim end (stim_end_sample_index), if in view
from IPython.display import display as _disp
_failed_viewer = make_failed_trials_viewer(_all_recordings_raw,
                                            pre_ms=10, post_ms=50)
_disp(_failed_viewer)

VBox(children=(ToggleButtons(options=(('All offline (43)', 'all'), ('No sync (39)', 'no_sync'), ('Alignment mi…

# Section 2c: Trial Exclusion & Pre-Analysis Filter

Runs **before** any analysis or DataFrame building. Two optional steps, applied in order:

1. **Failed-trial exclusion.** Removes the trials flagged by the Failed Trial Viewer above (default: its *All offline* group).
2. **Metric pre-filter.** Keeps only trials whose M-wave / H-wave / H:M ratio / background is within a target ± tolerance.

The apply cell reassigns `_all_recordings`, so **every cell below uses the cleaned data**. The untouched load stays in `_all_recordings_raw`, which the Failed Trial Viewer reads. Re-running is safe because the apply cell always starts from `_all_recordings_raw`.

Outputs: `excluded_trials_df` (one row per removed failed trial, `trial_idx` = the viewer's `trial [i]`) and `prefilter_metrics_df` (per-trial metrics + `kept`).

In [10]:
# ── Trial Exclusion & Pre-Filter Configuration ────────────────────────────────
# 1) Failed-trial exclusion
EXCLUDE_FAILED_TRIALS = True
# 'all' = the Failed Trial Viewer's "All offline" group: no sync, alignment miss,
# recalculated bad stim ADC, frozen stim ADC / sync (offline), onset mismatch.
# Or list keys, e.g. ['no_sync', 'recalc_stim', 'align_miss'].
# App flags ('app_stim', 'app_sync', 'app_both', 'app_vns') are opt-in only —
# the app's live frozen-run check over-flags clean trials.
EXCLUDE_CATEGORIES = 'all'
EXCLUDE_STAGES     = None     # None = all stages, or e.g. ['control_mode']

# 2) Metric pre-filter (applied after failed-trial exclusion)
PREFILTER_ENABLED = False
# Metric to filter on: 'M_WAVE' | 'H_WAVE' | 'HM_RATIO' | 'BACKGROUND'
PREFILTER_METRIC        = 'M_WAVE'
PREFILTER_TARGET        = 2000      # µV  (or dimensionless ratio for HM_RATIO)
PREFILTER_TOLERANCE_PCT = 25.0      # ±%  around target

PREFILTER_LO = PREFILTER_TARGET * (1 - PREFILTER_TOLERANCE_PCT / 100)
PREFILTER_HI = PREFILTER_TARGET * (1 + PREFILTER_TOLERANCE_PCT / 100)
# Uncomment to override with manual bounds instead:
# PREFILTER_LO = 100.0
# PREFILTER_HI = 200.0
PREFILTER_STAGES = None       # None = all stages, or e.g. ['control_mode']

print(f"Failed-trial exclusion : {'ON' if EXCLUDE_FAILED_TRIALS else 'OFF'}"
      f"  (categories={EXCLUDE_CATEGORIES!r}, stages={EXCLUDE_STAGES or 'all'})")
print(f"Metric pre-filter      : {'ON' if PREFILTER_ENABLED else 'OFF'}")
if PREFILTER_ENABLED:
    print(f"  Metric  : {PREFILTER_METRIC}")
    print(f"  Target  : {PREFILTER_TARGET}  ±{PREFILTER_TOLERANCE_PCT}%")
    print(f"  Bounds  : [{PREFILTER_LO:.2f},  {PREFILTER_HI:.2f}]")
    print(f"  Stages  : {PREFILTER_STAGES or 'all'}")

Failed-trial exclusion : ON  (categories='all', stages=all)
Metric pre-filter      : OFF

In [11]:
# ── Apply trial exclusion + pre-filter ────────────────────────────────────────
# Always starts from the raw load, so re-running with new settings is safe.
# Uses PRE_AVG_MS / POST_AVG_MS and the M/H window constants from the Configuration cell.
_all_recordings = _all_recordings_raw
excluded_trials_df   = None
prefilter_metrics_df = None

if EXCLUDE_FAILED_TRIALS:
    _all_recordings, excluded_trials_df = exclude_failed_trials(
        _all_recordings, categories=EXCLUDE_CATEGORIES, stages=EXCLUDE_STAGES)
else:
    print('Failed-trial exclusion OFF — failed trials kept.')
print()

if PREFILTER_ENABLED:
    _all_recordings, prefilter_metrics_df = filter_recordings_by_metric(
        _all_recordings, PREFILTER_METRIC, PREFILTER_LO, PREFILTER_HI,
        PRE_AVG_MS, POST_AVG_MS,
        M_WAVE_START_MS, M_WAVE_END_MS, H_WAVE_START_MS, H_WAVE_END_MS,
        stages=PREFILTER_STAGES)
else:
    print('Metric pre-filter OFF.')

print('\nAll cells below use the cleaned _all_recordings '
      '(raw data kept in _all_recordings_raw).')
excluded_trials_df

Failed-trial exclusion  (categories: all offline)
  CM1 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 847/847  (removed 0)
  CM2 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 1062/1074  (removed 12)
  CM3 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 788/805  (removed 17)
  CM4 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 808/808  (removed 0)
  CM5 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 788/800  (removed 12)
  CM6 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 953/953  (removed 0)
  CM7 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 990/990  (removed 0)
  CM8 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 589/589  (removed 0)
  CM9 HRPILOT-34 250US  [Control Mode (.hrs2)]:  kept 834/836  (removed 2)
  Total: kept 7659/7702  (99.4%),  removed 43
  Removed per category (a trial can hit several): Alignment miss=41, No sync=39, Frozen stim ADC (offline)=2, Recalculated bad stim ADC=39

Metric pre-filter OFF.

All cells below use the cleaned _all_recordings (raw data kept in _all_recordings_raw).

,recording,stage,trial_idx,amp_ma,categories,reasons
0,CM2 HRPILOT-34 250US,Control Mode (.hrs2),438,0.220,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
1,CM2 HRPILOT-34 250US,Control Mode (.hrs2),470,0.220,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
2,CM2 HRPILOT-34 250US,Control Mode (.hrs2),636,0.280,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
3,CM2 HRPILOT-34 250US,Control Mode (.hrs2),723,0.280,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
4,CM2 HRPILOT-34 250US,Control Mode (.hrs2),728,0.280,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
5,CM2 HRPILOT-34 250US,Control Mode (.hrs2),755,0.272,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
6,CM2 HRPILOT-34 250US,Control Mode (.hrs2),781,0.274,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
7,CM2 HRPILOT-34 250US,Control Mode (.hrs2),804,0.274,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
8,CM2 HRPILOT-34 250US,Control Mode (.hrs2),874,0.280,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
9,CM2 HRPILOT-34 250US,Control Mode (.hrs2),931,0.277,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
10,CM2 HRPILOT-34 250US,Control Mode (.hrs2),1072,0.257,align_miss,ALIGNMENT MISS — stored data
11,CM2 HRPILOT-34 250US,Control Mode (.hrs2),1073,0.257,align_miss,ALIGNMENT MISS — stored data
12,CM3 HRPILOT-34 250US,Control Mode (.hrs2),39,0.225,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
13,CM3 HRPILOT-34 250US,Control Mode (.hrs2),107,0.236,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
14,CM3 HRPILOT-34 250US,Control Mode (.hrs2),126,0.244,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
15,CM3 HRPILOT-34 250US,Control Mode (.hrs2),127,0.245,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
16,CM3 HRPILOT-34 250US,Control Mode (.hrs2),552,0.135,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
17,CM3 HRPILOT-34 250US,Control Mode (.hrs2),553,0.135,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
18,CM3 HRPILOT-34 250US,Control Mode (.hrs2),554,0.135,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
19,CM3 HRPILOT-34 250US,Control Mode (.hrs2),555,0.135,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
20,CM3 HRPILOT-34 250US,Control Mode (.hrs2),556,0.136,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
21,CM3 HRPILOT-34 250US,Control Mode (.hrs2),557,0.136,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
22,CM3 HRPILOT-34 250US,Control Mode (.hrs2),558,0.135,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
23,CM3 HRPILOT-34 250US,Control Mode (.hrs2),559,0.136,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
24,CM3 HRPILOT-34 250US,Control Mode (.hrs2),560,0.136,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
25,CM3 HRPILOT-34 250US,Control Mode (.hrs2),561,0.137,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
26,CM3 HRPILOT-34 250US,Control Mode (.hrs2),562,0.138,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
27,CM3 HRPILOT-34 250US,Control Mode (.hrs2),563,0.139,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
28,CM3 HRPILOT-34 250US,Control Mode (.hrs2),564,0.139,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
29,CM5 HRPILOT-34 250US,Control Mode (.hrs2),35,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
30,CM5 HRPILOT-34 250US,Control Mode (.hrs2),36,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
31,CM5 HRPILOT-34 250US,Control Mode (.hrs2),37,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
32,CM5 HRPILOT-34 250US,Control Mode (.hrs2),38,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
33,CM5 HRPILOT-34 250US,Control Mode (.hrs2),39,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
34,CM5 HRPILOT-34 250US,Control Mode (.hrs2),40,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
35,CM5 HRPILOT-34 250US,Control Mode (.hrs2),41,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
36,CM5 HRPILOT-34 250US,Control Mode (.hrs2),42,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
37,CM5 HRPILOT-34 250US,Control Mode (.hrs2),43,0.253,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
38,CM5 HRPILOT-34 250US,Control Mode (.hrs2),44,0.254,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
39,CM5 HRPILOT-34 250US,Control Mode (.hrs2),45,0.255,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
40,CM5 HRPILOT-34 250US,Control Mode (.hrs2),46,0.255,"align_miss, no_sync, recalc_stim",NO SYNC + ALIGNMENT MISS — stored data + Recal...
41,CM9 HRPILOT-34 250US,Control Mode (.hrs2),606,0.252,off_stim,Stim ADC frozen + app flag=8
42,CM9 HRPILOT-34 250US,Control Mode (.hrs2),696,0.248,off_stim,Stim ADC frozen + app flag=8

In [12]:
# ── Optional: Merged Amplitude Group Analysis ─────────────────────────────────
# MERGE_ALL = True  →  collapse every amplitude into a single group.
#
# MERGED_GROUPS accepts two styles (mix freely):
#   Explicit list : [0.12, 0.13, 0.15]   — merge exactly those amplitudes
#   Range tuple   : (0.10, 0.50)         — merge all amplitudes where low <= amp <= high
#
# Examples:
#   MERGED_GROUPS = [[0.12, 0.13], [0.15, 0.16, 0.17]]   ← two explicit groups
#   MERGED_GROUPS = [(0.10, 0.20), (0.25, 0.40)]          ← two range groups
#   MERGED_GROUPS = [(0.10, 0.20), [0.50, 0.55]]          ← range + explicit, mixed
#
# Leave both flags at their defaults to use the standard (unmerged) grouping.
MERGE_ALL     = True   # True → collapse every amplitude into one group
MERGED_GROUPS = []

def _resolve_groups(trials, groups):
    _all_amps = sorted({t.stimulation_amplitude_ma for t in trials})
    resolved = []
    for g in groups:
        if isinstance(g, tuple) and len(g) == 2:
            lo, hi = float(g[0]), float(g[1])
            matched = [a for a in _all_amps if lo <= a <= hi]
            if matched:
                resolved.append(matched)
            else:
                print(f'Warning: range ({lo}, {hi}) matched no amplitudes — skipped.')
        else:
            resolved.append(list(g))
    return resolved

def _apply_merge(trials):
    if MERGE_ALL:
        _amps = sorted({t.stimulation_amplitude_ma for t in trials})
        return build_merged_amp_groups(trials, [_amps])
    if MERGED_GROUPS:
        return build_merged_amp_groups(trials, _resolve_groups(trials, MERGED_GROUPS))
    return trials

print("Merge config: MERGE_ALL =", MERGE_ALL, " | MERGED_GROUPS =", MERGED_GROUPS or "(none)")
print("Re-run viewer cells or change Recording/Stage to apply new merge settings.")

Merge config: MERGE_ALL = True  | MERGED_GROUPS = (none)
Re-run viewer cells or change Recording/Stage to apply new merge settings.

In [13]:
# ── Pre-compute H-Reflex Comparison Data ──────────────────────────────────────────────
# Computed once here for instant rendering in the comparison plot below.
# Re-run this cell if you change PRE_AVG_MS, POST_AVG_MS, or H/M-wave window constants.
_xr_cache = compute_h_comparison_data(
    _all_recordings, PRE_AVG_MS, POST_AVG_MS,
    H_WAVE_START_MS, H_WAVE_END_MS,
    M_WAVE_START_MS, M_WAVE_END_MS,
)
_xr_stages = {}
for _rd in _all_recordings.values():
    for _sk, (_st, _sh, _se, _slbl) in _rd['stage_map'].items():
        if _st and _sk not in _xr_stages:
            _xr_stages[_sk] = _slbl
print(f'H-reflex comparison data pre-computed for {len(_xr_cache)} recording(s), '
      f'{len(_xr_stages)} stage(s): {list(_xr_stages.keys())}')

H-reflex comparison data pre-computed for 9 recording(s), 1 stage(s): ['control_mode']

In [14]:
# ── HRS2 Analysis: Interactive Averaged Waveforms + Recruitment Curve ──────────────────────────────────────────────────────────────────────
from IPython.display import display as _disp

def _render_ana(trials, header, emg_blocks, stage_label, rec_label, sr, h1h):
    _sr = sr or h1h.sample_rate
    tp = _apply_merge(trials)
    print(f'\n── Analysis: {stage_label}  ({len(trials)} trials)  [{rec_label}]')
    plot_hrs2_analysis(
        tp, header,
        pre_avg_ms=PRE_AVG_MS, post_avg_ms=POST_AVG_MS,
        n_per_page=N_PER_PAGE,
        m_start_ms=M_WAVE_START_MS, m_end_ms=M_WAVE_END_MS,
        h_start_ms=H_WAVE_START_MS, h_end_ms=H_WAVE_END_MS,
        sample_rate=_sr,
        emg_blocks=emg_blocks,
    )

_ana_widget, _ana_render = make_viewer(
    _all_recordings, _active_rec_label, _render_ana,
    stage_filter=lambda sk, *_a: sk != 'frequency_test',
)
_disp(_ana_widget)
_ana_render()

VBox(children=(Dropdown(description='Recording:', layout=Layout(width='600px'), options=('CM1 HRPILOT-34 250US…

# M-Wave Stabilization Control Error 

Plots the M-wave stabilization controller output trial-by-trial.
- **Left axis** — `m_wave_error` (µV): difference between actual M-wave and the target set-point; falls back to `m_wave_window_median` when the controller was inactive.
- **Right axis** — `stimulation_amplitude_ma` (mA, orange): stimulation intensity actually used.

In [15]:
# ── M-Wave Control Error with Reference Lines ─────────────────────────────────
# Controls:
#   Auto checkbox  — reads target M-size from the recording's stored set-value
#   Target (µV)    — manual override (editable when Auto is unchecked)
#   ±Inner %       — tolerance band drawn as green dashed lines around the target
#   ±Outer %       — algorithm bounds drawn as red dotted lines (set to 0 to hide)
#   Update Plot    — re-render with current settings after changing parameters
from ipywidgets import Checkbox, FloatText, FloatSlider, Button, Output, VBox, HBox, Label
from IPython.display import display as _disp
import numpy as np

def _mw_stage_filter(key, trials, header, emg_blocks, label):
    return bool(trials) and any(
        not np.isnan(getattr(t, 'm_wave_error', float('nan'))) or
        not np.isnan(getattr(t, 'm_wave_window_median', float('nan')))
        for t in trials)

def _mw_auto_target(trials):
    vals  = [getattr(t, 'm_wave_set_value_uv', float('nan')) for t in trials]
    valid = [v for v in vals if not np.isnan(v)]
    return float(np.median(valid)) if valid else float('nan')

# ── Control widgets ────────────────────────────────────────────────────────────
_mw_auto_cb   = Checkbox(value=True, description='Auto (recording set-value)',
                          style={'description_width': 'initial'}, layout={'width': '270px'})
_mw_target_ft = FloatText(value=0.0, description='Target (µV):',
                           step=10, disabled=True, layout={'width': '190px'})
_mw_inner_sl  = FloatSlider(value=25.0, min=0, max=100, step=1,
                              description='±Inner %:', readout_format='.0f',
                              style={'description_width': '70px'}, layout={'width': '280px'})
_mw_outer_sl  = FloatSlider(value=50.0, min=0, max=200, step=1,
                              description='±Outer %:', readout_format='.0f',
                              style={'description_width': '70px'}, layout={'width': '280px'})
_mw_apply_btn = Button(description='Update Plot', button_style='primary',
                        layout={'width': '120px'})
_mw_info_lbl  = Label(value='')

_mw_controls = VBox([
    HBox([_mw_auto_cb, _mw_target_ft, _mw_info_lbl]),
    HBox([_mw_inner_sl, _mw_outer_sl, _mw_apply_btn]),
])

def _render_mw(trials, header, emg_blocks, stage_label, rec_label, sr, h1h):
    if _mw_auto_cb.value:
        _auto = _mw_auto_target(trials)
        if not np.isnan(_auto):
            _mw_target_ft.value = _auto
            _mw_info_lbl.value  = f'Auto: {_auto:.1f} µV'
        else:
            _mw_info_lbl.value  = 'Auto: no set-value stored'
        _target = None
    else:
        _target = _mw_target_ft.value
        _mw_info_lbl.value = f'Override: {_target:.1f} µV'

    print(f'\n── M-Wave Control Error: {stage_label}  ({len(trials)} trials)  [{rec_label}]')
    plot_mwave_control_error(
        trials, header,
        sample_rate=sr or h1h.sample_rate,
        m_start_ms=M_WAVE_START_MS, m_end_ms=M_WAVE_END_MS,
        pre_ms=PRE_AVG_MS, post_ms=POST_AVG_MS,
        target_uv=_target,
        inner_pct=_mw_inner_sl.value,
        outer_pct=_mw_outer_sl.value,
    )

_has_any_mw = any(
    any(_mw_stage_filter(sk, _t, _h, _e, lbl)
        for sk, (_t, _h, _e, lbl) in rd['stage_map'].items())
    for rd in _all_recordings.values()
)

if _has_any_mw:
    _mw_widget, _mw_render = make_viewer(
        _all_recordings, _active_rec_label, _render_mw,
        stage_filter=_mw_stage_filter,
    )

    def _mw_auto_toggle(change):
        _mw_target_ft.disabled = change['new']
        _mw_render()

    _mw_auto_cb.observe(_mw_auto_toggle, names='value')
    _mw_apply_btn.on_click(lambda b: _mw_render())

    _disp(_mw_controls)
    _disp(_mw_widget)
    _mw_render()
else:
    print("No M-wave stabilization data available in any loaded recording "
          "(requires V3 S2 file_version ≥ 9, or S4/S5/S6 file_version ≥ 2).")

VBox(children=(HBox(children=(Checkbox(value=True, description='Auto (recording set-value)', layout=Layout(wid…

VBox(children=(Dropdown(description='Recording:', layout=Layout(width='600px'), options=('CM1 HRPILOT-34 250US…

# M-Wave Stabilization: Grouped by Distribution Window Size

Bar + whisker + per-trial-dots plot for recordings using the M-wave stabilization algorithm. Groups are detected from the per-trial stored `m_wave_distribution_window_size` (so a mid-recording change to that setting automatically shows up as its own group).

- **Bar height** = group mean
- **Whisker** = ±1 SD within the group
- **Dots** = every individual trial's own value

**Metric** toggle:
- **M-wave Size** (default) — each trial's own M-wave size (µV)
- **|Size − Set Value|** — `abs(m_wave_size - m_wave_set_value_uv)`: how far that trial's own M-wave size landed from the stabilizer's target

**Note:** `m_wave_distribution_window_size` isn't readable from the current file format yet (verified directly against real bytes — the already-known "opaque trailer" after the M-wave block doesn't contain it, it re-echoes `onset_sample_index`/`stim_end_sample_index` instead). Until the real byte position is found, every trial reports the same placeholder window size and this shows as a single group — the bar/whisker/dots and metric toggle are fully working today, just not yet split by window size.

In [16]:
# ── M-Wave Stabilization Groups ─────────────────────────────────────────────
# "Downsample to smallest group": when there are 2+ groups, every larger group is
# reduced to the smallest group's n (Fixed Intensity counts as a group).
#   Method  random — seeded draw without replacement (same seed → same subset)
#           even   — evenly spaced through the session
#           first  — earliest n trials
# Per-group n, mean, SD, CV (= SD/|mean|×100), median/IQR and stim amplitude are
# printed as tab-separated text below the plot — select + copy, pastes into Excel/Sheets.
from ipywidgets import ToggleButtons, Checkbox, Dropdown, IntText, VBox, HBox, Output
from IPython.display import display as _disp
from helpers import format_mwave_stabilization_summary
import numpy as np

def _mws_stage_filter(key, trials, header, emg_blocks, label):
    return bool(trials) and any(
        not np.isnan(getattr(t, 'm_wave_error', float('nan'))) or
        not np.isnan(getattr(t, 'm_wave_window_median', float('nan')))
        for t in trials)

_mws_metric_tog = ToggleButtons(
    options=[('M-wave Size', 'm_wave_size'), ('|Size − Set Value|', 'abs_error')],
    value='m_wave_size', description='Metric:',
)
_mws_ds_chk    = Checkbox(value=False, description='Downsample to smallest group',
                          indent=False, layout={'width': '230px'})
_mws_ds_method = Dropdown(options=['random', 'even', 'first'], value='random',
                          description='Method:', layout={'width': '180px'}, disabled=True)
_mws_ds_seed   = IntText(value=0, description='Seed:', layout={'width': '140px'}, disabled=True)

def _mws_on_ds(change):
    _mws_ds_method.disabled = not _mws_ds_chk.value
    _mws_ds_seed.disabled   = not _mws_ds_chk.value or _mws_ds_method.value != 'random'
    _mws_render()

_has_any_mws = any(
    any(_mws_stage_filter(sk, _t, _h, _e, lbl)
        for sk, (_t, _h, _e, lbl) in rd['stage_map'].items())
    for rd in _all_recordings.values()
)

if _has_any_mws:
    def _render_mws(trials, header, emg_blocks, stage_label, rec_label, sr, h1h):
        print(f'\n── M-Wave Stabilization Groups: {stage_label}  ({len(trials)} trials)  [{rec_label}]')
        _mws_summary = plot_mwave_stabilization_groups(
            trials, header, sr or h1h.sample_rate,
            m_start_ms=M_WAVE_START_MS, m_end_ms=M_WAVE_END_MS,
            pre_ms=PRE_AVG_MS, post_ms=POST_AVG_MS,
            metric=_mws_metric_tog.value,
            downsample=_mws_ds_chk.value,
            downsample_method=_mws_ds_method.value,
            downsample_seed=_mws_ds_seed.value,
        )
        if _mws_summary:
            print(format_mwave_stabilization_summary(_mws_summary))

    _mws_widget, _mws_render = make_viewer(
        _all_recordings, _active_rec_label, _render_mws,
        stage_filter=_mws_stage_filter,
    )
    _mws_metric_tog.observe(lambda c: _mws_render(), names='value')
    for _w in (_mws_ds_chk, _mws_ds_method, _mws_ds_seed):
        _w.observe(_mws_on_ds, names='value')
    _disp(VBox([_mws_metric_tog,
                HBox([_mws_ds_chk, _mws_ds_method, _mws_ds_seed]),
                _mws_widget]))
    _mws_render()
else:
    print("No M-wave stabilization data available in any loaded recording "
          "(requires V3 S2 file_version ≥ 9, or S4/S5/S6 file_version ≥ 2).")

VBox(children=(ToggleButtons(description='Metric:', options=(('M-wave Size', 'm_wave_size'), ('|Size − Set Val…

In [17]:
# ── HRS2 Trial Viewer: Interactive Per-Trial Grid + Zoom ──────────────────────
from IPython.display import display as _disp

def _render_trv(trials, header, emg_blocks, stage_label, rec_label, sr, h1h):
    tp = _apply_merge(trials)
    print(f'\n── Trial Viewer: {stage_label}  ({len(trials)} trials)  [{rec_label}]')
    plot_hrs2_trials(
        tp, header,
        pre_plot_ms=PRE_PLOT_MS, post_plot_ms=POST_PLOT_MS,
        n_per_page=N_PER_PAGE,
        m_start_ms=M_WAVE_START_MS, m_end_ms=M_WAVE_END_MS,
        h_start_ms=H_WAVE_START_MS, h_end_ms=H_WAVE_END_MS,
        sample_rate=sr or h1h.sample_rate,
        emg_blocks=emg_blocks,
    )

_trv_widget, _trv_render = make_viewer(
    _all_recordings, _active_rec_label, _render_trv,
    stage_filter=lambda sk, *_a: sk != 'frequency_test',
)
_disp(_trv_widget)
_trv_render()

VBox(children=(Dropdown(description='Recording:', layout=Layout(width='600px'), options=('CM1 HRPILOT-34 250US…

# Section 6c: Frequency Test Analysis (V3 FT)

Three views available via the **View** toggle:

- **H/M MRA Per Pulse** — mean ± 1σ H-wave and M-wave MRA at each pulse position across all trials. Uses `pulse_h_wave_mra` / `pulse_m_wave_mra` pre-stored by the app (mean rectified average within each window).
- **Avg Waveforms** — averaged pulse waveforms, paged.
- **H/M Peak Per Pulse** — max |EMG| within each wave window per pulse, computed from raw `trial_data`.

M/H wave windows are shared with the HRS2 configuration constants (`M_WAVE_START_MS`, `H_WAVE_START_MS`, etc.).

In [18]:
# ── Frequency Test Analysis: Interactive Viewer ─────────────────────────────
from IPython.display import display as _disp
_disp(make_ft_viewer(
    _all_recordings, POST_PLOT_MS,
    M_WAVE_START_MS, M_WAVE_END_MS,
    H_WAVE_START_MS, H_WAVE_END_MS,
))

Label(value='No Frequency Test data loaded (.hrft not found in any recording directory).')

# Section 6b: H-Reflex Size Across Recordings

**H-reflex size per amplitude group** = MRA of the averaged bipolar waveform in the H-wave window, minus the pre-stimulus background MRA:

> **size (µV) = mean|avg_bip(t ∈ [H_START, H_END])| − mean|avg_bip(t < 0)|**

One value per amplitude group; the box shows spread across amplitude groups.

In [ ]:
# ── H-Reflex Size Across Recordings: Comparison Plot ──────────────────────────────────────────────────────────
# Toggle between H-Reflex size, M-Wave size, and Background MRA (pre-stim EMG level).
# Optionally overlay a pooled mean +/- std ("Range average") computed across a
# contiguous range of recordings you pick below (drag either handle).
# The numbers behind the plot are printed as tab-separated text below it —
# select + copy, pastes into Excel/Sheets as columns.
# Re-run the pre-compute cell above if you change analysis configuration constants.
from ipywidgets import Dropdown, ToggleButtons, Checkbox, SelectionRangeSlider, Output, VBox, HBox, HTML
from helpers import format_h_comparison_summary
from IPython.display import display as _disp

_xr_stage_d = Dropdown(
    options=[(_slbl, _sk) for _sk, _slbl in _xr_stages.items()],
    description='Stage:', layout={'width': '480px'}
)
if _xr_stages:
    _xr_stage_d.value = next(iter(_xr_stages))

_xr_metric_d = ToggleButtons(
    options=[('H-Reflex Size', 'h_reflex'), ('M-Wave Size', 'm_wave'), ('Background MRA', 'background')],
    description='Metric:',
    style={'button_width': '160px'},
)

_xr_rec_labels = [lbl for lbl, _, _ in RECORDING_DIRS if lbl in _xr_cache] or ['']
_xr_range_chk = Checkbox(value=False, description='', indent=False,
                         layout={'width': '28px'})
_xr_range_lbl = HTML("<span style='font-size:16px; font-weight:bold'>Show range average</span>")
_xr_range_sl = SelectionRangeSlider(
    options=_xr_rec_labels,
    index=(0, len(_xr_rec_labels) - 1),
    description='Avg range:',
    layout={'width': '560px'},
    disabled=True,
)

_xr_out = Output()

def _xr_refresh():
    sk = _xr_stage_d.value
    mt = _xr_metric_d.value
    if not sk:
        return
    _rng = _xr_range_sl.value if _xr_range_chk.value else None
    with _xr_out:
        _xr_out.clear_output(wait=True)
        _xr_summary = plot_h_reflex_comparison(_xr_cache, RECORDING_DIRS, sk, _xr_stages, metric=mt,
                                 avg_range=_rng)
        if _xr_summary:
            print(format_h_comparison_summary(_xr_summary))

def _xr_on_range_chk(change):
    _xr_range_sl.disabled = not change['new']
    _xr_refresh()

_xr_stage_d.observe(lambda c: _xr_refresh(), names='value')
_xr_metric_d.observe(lambda c: _xr_refresh(), names='value')
_xr_range_chk.observe(_xr_on_range_chk, names='value')
_xr_range_sl.observe(lambda c: _xr_refresh(), names='value')
_disp(VBox([_xr_stage_d, _xr_metric_d, HBox([_xr_range_chk, _xr_range_lbl, _xr_range_sl]), _xr_out]))
_xr_refresh()

VBox(children=(Dropdown(description='Stage:', layout=Layout(width='480px'), options=(('Control Mode (.hrs2)', …

# Section 6d: Cross-Recording DataFrame & Calculations

`xr_df` is a flat per-trial DataFrame built from `_xr_cache`.  
Re-run this cell any time you re-run the pre-compute cell above.

In [20]:
import pandas as pd

# ── Build per-trial DataFrame from raw EMG ────────────────────────────────────
# Note: _xr_cache now stores per-amplitude-group averaged-waveform MRA (matching
# the waveform viewer). This DataFrame is independent — it computes metrics
# per individual trial directly from raw EMG for trial-level analysis.
_rows = []
for _rec_lbl, _rec in _all_recordings.items():
    _sr_xr    = _rec['sample_rate'] or SAMPLE_RATE
    _ms_ps_xr = 1000.0 / _sr_xr
    _rec_s_xr = int(TRIAL_RECORD_MS * _sr_xr / 1000)
    for _sk, (_trials, _hdr, _emg_bl, _slbl) in _rec['stage_map'].items():
        for _i, _t in enumerate(_trials):
            try:
                _tm, _et, *_ = get_trial_window(
                    _t, PRE_AVG_MS, POST_AVG_MS,
                    ms_per_sample=_ms_ps_xr, record_samples=_rec_s_xr)
                _bg_v = compute_peri_stim_bg(_t, _sr_xr)
                if np.isnan(_bg_v): _bg_v = 0.0
                _mm   = (_tm >= M_WAVE_START_MS) & (_tm <= M_WAVE_END_MS)
                _hm   = (_tm >= H_WAVE_START_MS) & (_tm <= H_WAVE_END_MS)
                _mv   = float(np.nanmean(np.abs(_et[_mm]))) - _bg_v if _mm.any() else float('nan')
                _hv   = float(np.nanmean(np.abs(_et[_hm]))) - _bg_v if _hm.any() else float('nan')
            except Exception:
                _mv = _hv = _bg_v = float('nan')
            _rows.append({
                'recording': _rec_lbl,
                'stage':     _slbl,
                'trial':     _i + 1,
                'h_size_uv': _hv,
                'm_size_uv': _mv,
                'bg_mra_uv': _bg_v,
                'hm_ratio':  _hv / _mv if (_mv and _mv > 0 and not np.isnan(_mv)) else float('nan'),
            })

xr_df = pd.DataFrame(_rows)
print(f"xr_df: {len(xr_df)} rows  (per-trial rectified EMG metrics)")
print(f"  recordings: {xr_df['recording'].nunique()}  |  stages: {xr_df['stage'].nunique()}")
xr_df.head(10)

xr_df: 7659 rows  (per-trial rectified EMG metrics)
  recordings: 9  |  stages: 1

,recording,stage,trial,h_size_uv,m_size_uv,bg_mra_uv,hm_ratio
0,CM1 HRPILOT-34 250US,Control Mode (.hrs2),1,210.596014,577.676184,220.392359,0.364557
1,CM1 HRPILOT-34 250US,Control Mode (.hrs2),2,-51.848724,520.153901,307.357635,-0.099680
2,CM1 HRPILOT-34 250US,Control Mode (.hrs2),3,-2.784712,969.925005,311.107588,-0.002871
3,CM1 HRPILOT-34 250US,Control Mode (.hrs2),4,-90.063373,555.606976,357.583393,-0.162099
4,CM1 HRPILOT-34 250US,Control Mode (.hrs2),5,379.790087,1275.379930,226.751906,0.297786
5,CM1 HRPILOT-34 250US,Control Mode (.hrs2),6,-137.320123,653.702490,393.561304,-0.210065
6,CM1 HRPILOT-34 250US,Control Mode (.hrs2),7,603.818969,607.427123,277.790955,0.994060
7,CM1 HRPILOT-34 250US,Control Mode (.hrs2),8,-261.766345,811.280041,373.291736,-0.322658
8,CM1 HRPILOT-34 250US,Control Mode (.hrs2),9,233.500446,374.959430,196.939862,0.622735
9,CM1 HRPILOT-34 250US,Control Mode (.hrs2),10,154.051095,268.999276,209.813071,0.572682

In [21]:
# ── Per-recording summary statistics ─────────────────────────────────────────
xr_summary = (
    xr_df.groupby('recording')
    .agg(
        n_trials      = ('trial',      'count'),
        h_size_mean   = ('h_size_uv',  'mean'),
        h_size_std    = ('h_size_uv',  'std'),
        m_size_mean   = ('m_size_uv',  'mean'),
        m_size_std    = ('m_size_uv',  'std'),
        bg_mra_mean   = ('bg_mra_uv',  'mean'),
        hm_ratio_mean = ('hm_ratio',   'mean'),
        hm_ratio_std  = ('hm_ratio',   'std'),
    )
    .round(3)
)
xr_summary

,n_trials,h_size_mean,h_size_std,m_size_mean,m_size_std,bg_mra_mean,hm_ratio_mean,hm_ratio_std
recording,,,,,,,,
CM1 HRPILOT-34 250US,847,281.180,283.608,1759.350,507.491,320.430,0.155,0.726
CM2 HRPILOT-34 250US,1062,418.438,355.126,1528.024,739.647,267.615,0.395,1.092
CM3 HRPILOT-34 250US,788,289.038,364.072,618.644,499.391,313.920,1.155,4.458
CM4 HRPILOT-34 250US,808,279.466,293.210,1024.682,546.213,301.668,0.504,1.701
CM5 HRPILOT-34 250US,788,440.171,413.643,1501.261,918.672,323.250,-0.004,7.380
CM6 HRPILOT-34 250US,953,443.481,447.209,1504.004,1021.302,322.055,0.355,3.964
CM7 HRPILOT-34 250US,990,255.625,349.661,671.397,764.074,304.631,0.480,15.222
CM8 HRPILOT-34 250US,589,403.221,332.305,871.634,898.622,292.666,2.717,29.487
CM9 HRPILOT-34 250US,834,390.797,382.184,909.543,567.860,309.342,0.662,1.662

### Recording Settings DataFrame

`settings_df` captures the app-side stimulation/window settings that were active for each
(recording, stage) — parsed from the `*.settings.json` sidecar written next to each binary
data file by newer H-Reflex App recordings (sweep range, M/H-wave windows, thresholds,
polarity, pulse-train parameters, etc). Stages recorded before the app wrote sidecars still
get a row here; their settings columns are simply NaN.

In [22]:
# ── Build settings DataFrame from *.settings.json sidecars ───────────────────────
settings_df = build_settings_dataframe(_all_recordings)
_meta_cols = {'recording', 'stage', 'stage_key', 'subject_id', 'session_start',
              'app_version', 'file_version', 'sample_rate_hz', 'n_trials'}
_setting_cols = [c for c in settings_df.columns if c not in _meta_cols]
_n_with_settings = int(settings_df[_setting_cols].notna().any(axis=1).sum()) if _setting_cols else 0
print(f"settings_df: {len(settings_df)} rows  |  {settings_df['recording'].nunique()} recording(s)  |  "
      f"{_n_with_settings}/{len(settings_df)} stage(s) have a settings.json sidecar")
settings_df.head(10)

settings_df: 9 rows  |  9 recording(s)  |  8/9 stage(s) have a settings.json sidecar

,recording,stage,stage_key,subject_id,session_start,app_version,file_version,sample_rate_hz,n_trials,user_min_stimulation_amplitude,...,user_m_wave_window_start_time_milliseconds,user_m_wave_window_end_time_milliseconds,user_h_wave_window_start_time_milliseconds,user_h_wave_window_end_time_milliseconds,manual_min_threshold,manual_max_threshold,reversed_polarity,fixed_stimulation_amplitude_ma,filtering_protocol,m_wave_stabilization_fixed
0,CM1 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-09-24 08:29:42.844809,H-Reflex App Version 3,14,55000.0,847,0.220,...,2.2,4.2,6.0,10.0,150.0,600.0,False,0.220,OFFLINE,NaN
1,CM2 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-09-25 09:51:36.278750,H-Reflex App Version 3,14,55000.0,1062,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CM3 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-09-28 13:08:34.157930,H-Reflex App Version 3,14,55000.0,788,0.220,...,2.0,4.0,6.0,10.0,215.0,475.0,False,0.220,OFFLINE,NaN
3,CM4 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-09-30 09:30:06.200553,H-Reflex App Version 3,14,55000.0,808,0.220,...,2.0,4.0,6.0,10.0,230.0,450.0,False,0.220,OFFLINE,NaN
4,CM5 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-10-01 10:21:36.317065,H-Reflex App Version 3,17,40000.0,788,0.220,...,2.0,4.0,6.0,10.0,230.0,475.0,False,0.220,OFFLINE,False
5,CM6 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-10-02 09:42:39.586931,H-Reflex App Version 3,17,40000.0,953,0.220,...,2.0,4.0,6.0,10.0,200.0,465.0,False,0.220,OFFLINE,False
6,CM7 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-10-05 12:02:16.433197,H-Reflex App Version 3,17,55000.0,990,0.220,...,2.0,4.0,6.0,10.0,250.0,465.0,False,0.220,OFFLINE,False
7,CM8 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-10-06 10:32:42.678066,H-Reflex App Version 3,17,55000.0,589,0.220,...,2.0,4.0,6.0,10.0,230.0,465.0,False,0.220,OFFLINE,False
8,CM9 HRPILOT-34 250US,Control Mode (.hrs2),control_mode,HRPILOT-34,2026-10-07 10:22:03.153904,H-Reflex App Version 3,17,55000.0,834,0.284,...,2.0,4.0,6.0,10.0,245.0,465.0,False,0.284,OFFLINE,False

### Save Analysis to Disk

Bundle `xr_df`, `xr_summary`, and `settings_df` into a single pickle file so this analysis
can be reloaded later without re-reading the raw binary recordings. Call
`save_analysis_pickle()` whenever you want a snapshot — nothing is saved automatically.

In [23]:
# ── Save analysis DataFrames to a pickle file (on demand) ──────────────
import pickle
from datetime import datetime as _dt

def save_analysis_pickle(path=None, **extra_frames):
    """Pickle xr_df, xr_summary, and settings_df (plus any extra_frames) to *path*.

    path=None auto-names the file from the current timestamp in the working directory.
    Returns the path written to.
    """
    _path = path or f"h_reflex_analysis_{_dt.now():%Y%m%d_%H%M%S}.pkl"
    _bundle = {'xr_df': xr_df, 'xr_summary': xr_summary, 'settings_df': settings_df, **extra_frames}
    with open(_path, 'wb') as _f:
        pickle.dump(_bundle, _f)
    print(f"Saved {list(_bundle.keys())} -> {_path}")
    return _path

print("Ready. Call save_analysis_pickle() to pickle xr_df / xr_summary / settings_df to disk,")
print("or save_analysis_pickle('my_analysis.pkl') to choose the filename.")

Ready. Call save_analysis_pickle() to pickle xr_df / xr_summary / settings_df to disk,
or save_analysis_pickle('my_analysis.pkl') to choose the filename.

In [24]:
# ── M-wave size: pool first 4 recordings and compute grand mean ± SD ──────────
_baseline_recs = ['HRPILOT-17 CM1', 'HRPILOT-17 CM2', 'HRPILOT-17 CM3', 'HRPILOT-17 CM4', 'HRPILOT-17 CM5', 'HRPILOT-17 CM6', 'HRPILOT-17 CM7']

_pool = xr_df[xr_df['recording'].isin(_baseline_recs)]['m_size_uv'].dropna()

_grand_mean = _pool.mean()
_grand_std  = _pool.std(ddof=1)
_n_trials   = len(_pool)

print(f"M-wave size  (pooled across {_baseline_recs}):")
print(f"  N trials : {_n_trials}")
print(f"  Mean     : {_grand_mean:.3f} µV")
print(f"  SD       : {_grand_std:.3f} µV")
print()

# Per-recording breakdown for reference
print("Per-recording:")
for _rl in _baseline_recs:
    _d = xr_df[xr_df['recording'] == _rl]['m_size_uv'].dropna()
    print(f"  {_rl}: n={len(_d)}  mean={_d.mean():.3f}  SD={_d.std(ddof=1):.3f} µV")

M-wave size  (pooled across ['HRPILOT-17 CM1', 'HRPILOT-17 CM2', 'HRPILOT-17 CM3', 'HRPILOT-17 CM4', 'HRPILOT-17 CM5', 'HRPILOT-17 CM6', 'HRPILOT-17 CM7']):
  N trials : 0
  Mean     : nan µV
  SD       : nan µV

Per-recording:
  HRPILOT-17 CM1: n=0  mean=nan  SD=nan µV
  HRPILOT-17 CM2: n=0  mean=nan  SD=nan µV
  HRPILOT-17 CM3: n=0  mean=nan  SD=nan µV
  HRPILOT-17 CM4: n=0  mean=nan  SD=nan µV
  HRPILOT-17 CM5: n=0  mean=nan  SD=nan µV
  HRPILOT-17 CM6: n=0  mean=nan  SD=nan µV
  HRPILOT-17 CM7: n=0  mean=nan  SD=nan µV

# Section 6e: Trial Subset Filter

Filter every recording's trials by a per-trial EMG metric before analysis.  
Set `FILTER_TARGET` to your desired M-wave (or other) size, and `FILTER_TOLERANCE_PCT` to the ± window.  
Running the filter cell creates `_filtered_recordings` — a drop-in replacement for `_all_recordings` used by the comparison plot below.  
`xr_df_filtered` is the filtered subset of the DataFrame for calculations.

In [25]:
# ── Trial Filter Configuration ─────────────────────────────────────────────────
# Metric to filter on: 'M_WAVE' | 'H_WAVE' | 'HM_RATIO' | 'BACKGROUND'
FILTER_METRIC        = 'M_WAVE'
FILTER_TARGET        = 2550      # µV  (or dimensionless ratio for HM_RATIO)
FILTER_TOLERANCE_PCT = 25.0       # ±%  around target

FILTER_LO = FILTER_TARGET * (1 - FILTER_TOLERANCE_PCT / 100)
FILTER_HI = FILTER_TARGET * (1 + FILTER_TOLERANCE_PCT / 100)
# Uncomment to override with manual bounds instead:
# FILTER_LO = 100.0
# FILTER_HI = 200.0

print(f"Metric  : {FILTER_METRIC}")
print(f"Target  : {FILTER_TARGET}  ±{FILTER_TOLERANCE_PCT}%")
print(f"Bounds  : [{FILTER_LO:.2f},  {FILTER_HI:.2f}]")

Metric  : M_WAVE
Target  : 2550  ±25.0%
Bounds  : [1912.50,  3187.50]

In [26]:
# ── Apply per-trial filter ─────────────────────────────────────────────────────
# Computes the chosen metric from raw EMG for every trial, keeps those in [FILTER_LO, FILTER_HI].
# Creates:
#   _filtered_recordings  — same structure as _all_recordings, with only passing trials
#   xr_df_filtered        — filtered subset of xr_df for DataFrame calculations

_filtered_recordings = {}
for _rec_lbl, _rec in _all_recordings.items():
    _sr_f    = _rec['sample_rate'] or SAMPLE_RATE
    _ms_ps_f = 1000.0 / _sr_f
    _rec_s_f = int(TRIAL_RECORD_MS * _sr_f / 1000)
    _filt_sm = {}
    for _sk, (_trials, _hdr, _emg_bl, _slbl) in _rec['stage_map'].items():
        _keep = []
        for _t in _trials:
            try:
                _tm, _et, *_ = get_trial_window(
                    _t, PRE_AVG_MS, POST_AVG_MS,
                    ms_per_sample=_ms_ps_f, record_samples=_rec_s_f,
                )
                _bg_v = compute_peri_stim_bg(_t, _sr_f)
                if np.isnan(_bg_v): _bg_v = 0.0
                if FILTER_METRIC == 'M_WAVE':
                    _wm = (_tm >= M_WAVE_START_MS) & (_tm <= M_WAVE_END_MS)
                    _val = float(np.nanmean(np.abs(_et[_wm]))) - _bg_v if _wm.any() else float('nan')
                elif FILTER_METRIC == 'H_WAVE':
                    _wm = (_tm >= H_WAVE_START_MS) & (_tm <= H_WAVE_END_MS)
                    _val = float(np.nanmean(np.abs(_et[_wm]))) - _bg_v if _wm.any() else float('nan')
                elif FILTER_METRIC == 'BACKGROUND':
                    _val = _bg_v
                elif FILTER_METRIC == 'HM_RATIO':
                    _mm = (_tm >= M_WAVE_START_MS) & (_tm <= M_WAVE_END_MS)
                    _hm = (_tm >= H_WAVE_START_MS) & (_tm <= H_WAVE_END_MS)
                    _mv = float(np.nanmean(np.abs(_et[_mm]))) - _bg_v if _mm.any() else float('nan')
                    _hv = float(np.nanmean(np.abs(_et[_hm]))) - _bg_v if _hm.any() else float('nan')
                    _val = (_hv / _mv) if (_mv and not np.isnan(_mv) and _mv > 0) else float('nan')
                else:
                    _val = float('nan')
            except Exception:
                _val = float('nan')
            if not np.isnan(_val) and FILTER_LO <= _val <= FILTER_HI:
                _keep.append(_t)
        _filt_sm[_sk] = (_keep, _hdr, _emg_bl, _slbl)
    _filtered_recordings[_rec_lbl] = {**_rec, 'stage_map': _filt_sm}

# ── Filtered DataFrame (from xr_df by metric column) ──────────────────────────
_filt_col = {
    'M_WAVE': 'm_size_uv', 'H_WAVE': 'h_size_uv',
    'HM_RATIO': 'hm_ratio', 'BACKGROUND': 'bg_mra_uv',
}.get(FILTER_METRIC, 'm_size_uv')
xr_df_filtered = xr_df[
    (xr_df[_filt_col] >= FILTER_LO) & (xr_df[_filt_col] <= FILTER_HI)
].copy().reset_index(drop=True)

# ── Summary ────────────────────────────────────────────────────────────────────
print(f"Filter: {FILTER_METRIC}  in  [{FILTER_LO:.2f}, {FILTER_HI:.2f}]\n")
_tot_orig = _tot_kept = 0
for _rl, _fr in _filtered_recordings.items():
    for _sk, (_ft, *_) in _fr['stage_map'].items():
        _orig = len(_all_recordings[_rl]['stage_map'][_sk][0])
        _kept = len(_ft)
        _tot_orig += _orig
        _tot_kept += _kept
        _pct = 100 * _kept / _orig if _orig else 0
        print(f"  {_rl}  [{_all_recordings[_rl]['stage_map'][_sk][3]}]:"
              f"  {_kept}/{_orig} trials  ({_pct:.1f}%)")
if _tot_orig:
    print(f"\n  Total: {_tot_kept}/{_tot_orig} trials  ({100*_tot_kept/_tot_orig:.1f}%)")
print(f"\nxr_df_filtered: {len(xr_df_filtered)} / {len(xr_df)} rows")

Filter: M_WAVE  in  [1912.50, 3187.50]

  CM1 HRPILOT-34 250US  [Control Mode (.hrs2)]:  329/847 trials  (38.8%)
  CM2 HRPILOT-34 250US  [Control Mode (.hrs2)]:  279/1062 trials  (26.3%)
  CM3 HRPILOT-34 250US  [Control Mode (.hrs2)]:  15/788 trials  (1.9%)
  CM4 HRPILOT-34 250US  [Control Mode (.hrs2)]:  53/808 trials  (6.6%)
  CM5 HRPILOT-34 250US  [Control Mode (.hrs2)]:  263/788 trials  (33.4%)
  CM6 HRPILOT-34 250US  [Control Mode (.hrs2)]:  359/953 trials  (37.7%)
  CM7 HRPILOT-34 250US  [Control Mode (.hrs2)]:  62/990 trials  (6.3%)
  CM8 HRPILOT-34 250US  [Control Mode (.hrs2)]:  74/589 trials  (12.6%)
  CM9 HRPILOT-34 250US  [Control Mode (.hrs2)]:  37/834 trials  (4.4%)

  Total: 1471/7659 trials  (19.2%)

xr_df_filtered: 1471 / 7659 rows

In [27]:
# ── Filtered Comparison Plot + Waveform Viewer ────────────────────────────────────────────────────────
# Re-run this cell any time you change the filter bounds above.
from ipywidgets import Dropdown, ToggleButtons, Output, VBox
from IPython.display import display as _disp
from helpers import format_h_comparison_summary

_xr_cache_filt = compute_h_comparison_data(
    _filtered_recordings, PRE_AVG_MS, POST_AVG_MS,
    H_WAVE_START_MS, H_WAVE_END_MS,
    M_WAVE_START_MS, M_WAVE_END_MS,
)

# ── Comparison boxplot ──────────────────────────────────────────────────────────────────────────
_xr_filt_out = Output()

def _xr_filt_render():
    _sk = _xr_filt_stage_d.value
    _mt = _xr_filt_metric_d.value
    if not _sk:
        return
    with _xr_filt_out:
        _xr_filt_out.clear_output(wait=True)
        _xr_filt_summary = plot_h_reflex_comparison(
            _xr_cache_filt, RECORDING_DIRS, _sk, _xr_stages, metric=_mt)
        if _xr_filt_summary:
            print(format_h_comparison_summary(_xr_filt_summary))

_xr_filt_stage_d = Dropdown(
    options=[(_slbl, _sk) for _sk, _slbl in _xr_stages.items()],
    description='Stage:', layout={'width': '480px'},
)
if _xr_stages:
    _xr_filt_stage_d.value = next(iter(_xr_stages))

_xr_filt_metric_d = ToggleButtons(
    options=[('H-Reflex Size', 'h_reflex'), ('M-Wave Size', 'm_wave'), ('Background MRA', 'background')],
    description='Metric:', style={'button_width': '160px'},
)

_xr_filt_stage_d.observe(lambda c: _xr_filt_render(), names='value')
_xr_filt_metric_d.observe(lambda c: _xr_filt_render(), names='value')
_disp(VBox([_xr_filt_stage_d, _xr_filt_metric_d, _xr_filt_out]))
_xr_filt_render()

# ── Filtered waveform analysis viewer ──────────────────────────────────────────────────────────────
_fw_out = Output()

def _fw_stage_opts(rec_lbl):
    return [(lbl, sk)
            for sk, (_t, _h, _e, lbl) in _filtered_recordings[rec_lbl]['stage_map'].items()]

def _fw_render():
    _rl  = _fw_rec_d.value
    _sk2 = _fw_stage_d.value
    if not _rl or not _sk2:
        return
    _fr  = _filtered_recordings[_rl]
    _ft, _fh, _fe, _slbl = _fr['stage_map'][_sk2]
    _sr2 = _fr['sample_rate']
    _tp  = _apply_merge(_ft)
    with _fw_out:
        _fw_out.clear_output(wait=True)
        print(f'\n── Filtered Waveforms: {_slbl}  ({len(_ft)} filtered trials)  [{_rl}]')
        if not _ft:
            print('No trials pass the current filter for this recording/stage.')
            return
        plot_hrs2_analysis(
            _tp, _fh,
            pre_avg_ms=PRE_AVG_MS, post_avg_ms=POST_AVG_MS,
            n_per_page=N_PER_PAGE,
            m_start_ms=M_WAVE_START_MS, m_end_ms=M_WAVE_END_MS,
            h_start_ms=H_WAVE_START_MS, h_end_ms=H_WAVE_END_MS,
            sample_rate=_sr2,
            emg_blocks=_fe,
        )

_fw_rec_d = Dropdown(
    options=list(_filtered_recordings.keys()),
    value=next(iter(_filtered_recordings)),
    description='Recording:', layout={'width': '640px'},
)
_fw_stage_d = Dropdown(
    options=_fw_stage_opts(next(iter(_filtered_recordings))),
    description='Stage:', layout={'width': '480px'},
)

def _fw_on_rec(change):
    _fw_stage_d.unobserve(_fw_on_stage, names='value')
    _opts = _fw_stage_opts(_fw_rec_d.value)
    _fw_stage_d.options = _opts
    _fw_stage_d.value   = _opts[0][1] if _opts else None
    _fw_stage_d.observe(_fw_on_stage, names='value')
    _fw_render()

def _fw_on_stage(change):
    _fw_render()

_fw_rec_d.observe(_fw_on_rec,     names='value')
_fw_stage_d.observe(_fw_on_stage, names='value')

_fw_ctrl = VBox([_fw_rec_d, _fw_stage_d]) if len(_filtered_recordings) > 1 else VBox([_fw_stage_d])
_disp(VBox([_fw_ctrl, _fw_out]))
_fw_render()

VBox(children=(Dropdown(description='Stage:', layout=Layout(width='480px'), options=(('Control Mode (.hrs2)', …

VBox(children=(VBox(children=(Dropdown(description='Recording:', layout=Layout(width='640px'), options=('CM1 H…

Merged group ['0.203', '0.205', '0.206', '0.207', '0.208', '0.210', '0.211', '0.212', '0.213', '0.214', '0.215', '0.216', '0.217', '0.218', '0.219', '0.220', '0.221', '0.222', '0.223', '0.224', '0.225', '0.226', '0.227', '0.228', '0.229', '0.230', '0.231', '0.232', '0.233', '0.234', '0.235', '0.236', '0.237', '0.238', '0.239', '0.240', '0.241', '0.242', '0.243', '0.244', '0.246', '0.247', '0.248', '0.249', '0.250', '0.252', '0.253', '0.254', '0.255', '0.256', '0.258', '0.259', '0.260', '0.268', '0.269', '0.270', '0.272', '0.276', '0.277', '0.278', '0.279', '0.280'] mA -> avg 0.238 mA, 329 trials

# Section 3c: H:M Ratio Summary

Box plot and histogram of H:M ratio for each stimulation polarity group.
If both normal and reversed polarities were used in this session, each group is analysed separately.

In [28]:
# ── Stim Polarity Analysis ────────────────────────────────────────────────────
from IPython.display import display as _disp

def _render_pol(trials, header, emg_blocks, stage_label, rec_label, sr, h1h):
    print(f'\n── Polarity / H:M Ratio: {stage_label}  ({len(trials)} trials)  [{rec_label}]')
    trials_by_polarity = split_trials_by_polarity(trials)
    plot_hm_ratio_summary(
        trials_by_polarity, header,
        m_start_ms=M_WAVE_START_MS, m_end_ms=M_WAVE_END_MS,
        h_start_ms=H_WAVE_START_MS, h_end_ms=H_WAVE_END_MS,
        sample_rate=sr or h1h.sample_rate,
        pre_ms=PRE_AVG_MS, post_ms=POST_AVG_MS,
    )
    plot_hwave_regression(
        trials, emg_blocks,
        m_start_ms=M_WAVE_START_MS, m_end_ms=M_WAVE_END_MS,
        h_start_ms=H_WAVE_START_MS, h_end_ms=H_WAVE_END_MS,
        sample_rate=sr or h1h.sample_rate,
        pre_ms=PRE_AVG_MS, post_ms=POST_AVG_MS,
    )

_pol_widget, _pol_render = make_viewer(_all_recordings, _active_rec_label, _render_pol)
_disp(_pol_widget)
_pol_render()

VBox(children=(Dropdown(description='Recording:', layout=Layout(width='600px'), options=('CM1 HRPILOT-34 250US…